### PR TITLE
tests should fail for good reasons only

### PR DESCRIPTION
**Pull request by mdeff**
Fixes the following test error that happened far too often.

### CODE REVIEW

**Comment by mdeff** [comment]
And that's the key retrieval issue that often pops up as well.

**Comment by mdeff** [comment]
Another kind of false test failures is the verification of hyperlinks. But that's pretty useful as hyperlinks tend to break now and then. We could run it without enforcing it to succeed, but I'm not sure whether we'll pay attention to it if it never fails.

`http://tulip.labri.fr` fails especially often.

**Comment by mdeff** [comment]
Newer sphinx will handle rate-limits in `linkcheck` https://github.com/sphinx-doc/sphinx/commit/6b90a63f0862f4cbc31621d0daff8f52fde3ee64. That should also help.

**Review by nperraud — APPROVED** [review]
All is good.

Good improvement to the function graph_sparsify

Thanks

**Pull request merged**
